#!/usr/bin/env bash
# Build a release APK locally without Expo cloud.
#
# First run generates a release keystore (saved to android/app/bookly-release.keystore)
# and writes credentials to android/keystore.properties (gitignored).
# Subsequent runs reuse them.
#
# Override any credential via env vars: BOOKLY_KS_PASSWORD, BOOKLY_KEY_ALIAS, BOOKLY_KEY_PASSWORD.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ANDROID_DIR="$ROOT/android"
APP_DIR="$ANDROID_DIR/app"
KEYSTORE_NAME="bookly-release.keystore"
KEYSTORE_PATH="$APP_DIR/$KEYSTORE_NAME"
PROPS_FILE="$ANDROID_DIR/keystore.properties"

VARIANT="${1:-release}"  # release | debug

log() { printf "\033[1;36m[build-apk]\033[0m %s\n" "$*"; }
err() { printf "\033[1;31m[build-apk]\033[0m %s\n" "$*" >&2; }

# --- 1. Check JDK 17 ---
if ! command -v java >/dev/null 2>&1 || ! java -version 2>&1 | grep -qE '"(17|21)'; then
  err "JDK 17 (or 21) not found. Install first:"
  err "  brew install --cask temurin@17"
  err "Then in ~/.zshrc add:"
  err "  export JAVA_HOME=\$(/usr/libexec/java_home -v 17)"
  exit 1
fi

# --- 2. Check Android SDK ---
if [ -z "${ANDROID_HOME:-}" ] && [ -z "${ANDROID_SDK_ROOT:-}" ]; then
  DEFAULT_SDK="$HOME/Library/Android/sdk"
  if [ -d "$DEFAULT_SDK" ]; then
    export ANDROID_HOME="$DEFAULT_SDK"
    log "Using ANDROID_HOME=$ANDROID_HOME"
  else
    err "ANDROID_HOME not set. Install Android Studio → SDK (API 34+)."
    err "Then in ~/.zshrc add:"
    err "  export ANDROID_HOME=\$HOME/Library/Android/sdk"
    exit 1
  fi
fi

# --- 3. Generate release keystore on first run ---
if [ "$VARIANT" = "release" ] && [ ! -f "$KEYSTORE_PATH" ]; then
  log "No release keystore found. Generating $KEYSTORE_NAME ..."
  KS_PASS="${BOOKLY_KS_PASSWORD:-bookly$(date +%s | sha256sum | head -c 8)}"
  KEY_ALIAS="${BOOKLY_KEY_ALIAS:-bookly}"
  KEY_PASS="${BOOKLY_KEY_PASSWORD:-$KS_PASS}"

  keytool -genkeypair -v \
    -keystore "$KEYSTORE_PATH" \
    -alias "$KEY_ALIAS" \
    -keyalg RSA -keysize 2048 -validity 10000 \
    -storepass "$KS_PASS" \
    -keypass "$KEY_PASS" \
    -dname "CN=Bookly, OU=NightIndie, O=NightIndie, L=HCM, S=HCM, C=VN"

  cat > "$PROPS_FILE" <<EOF
# Auto-generated by scripts/build-apk.sh (gitignored)
BOOKLY_RELEASE_STORE_FILE=$KEYSTORE_NAME
BOOKLY_RELEASE_STORE_PASSWORD=$KS_PASS
BOOKLY_RELEASE_KEY_ALIAS=$KEY_ALIAS
BOOKLY_RELEASE_KEY_PASSWORD=$KEY_PASS
EOF
  log "Saved credentials to $PROPS_FILE (keep private)."
fi

# --- 4. Load keystore credentials into gradle properties ---
GRADLE_ARGS=()
if [ -f "$PROPS_FILE" ]; then
  while IFS='=' read -r k v; do
    [[ "$k" =~ ^#.*$ || -z "$k" ]] && continue
    GRADLE_ARGS+=("-P$k=$v")
  done < "$PROPS_FILE"
fi

# --- 5. (Optional) full clean — pass --clean as 2nd arg to force. Otherwise skip for fast
# incremental builds; running gradle clean can crash the CMake external-build graph.
cd "$ANDROID_DIR"
if [ "${2:-}" = "--clean" ]; then
  log "Full clean requested..."
  rm -rf app/.cxx app/build build
  ./gradlew clean >/dev/null || true
fi

# --- 6. Build ---
if [ "$VARIANT" = "debug" ]; then
  log "Building debug APK..."
  ./gradlew assembleDebug "${GRADLE_ARGS[@]}"
  OUT="$APP_DIR/build/outputs/apk/debug/app-debug.apk"
else
  log "Building release APK..."
  ./gradlew assembleRelease "${GRADLE_ARGS[@]}"
  OUT="$APP_DIR/build/outputs/apk/release/app-release.apk"
fi

if [ -f "$OUT" ]; then
  SIZE=$(du -h "$OUT" | awk '{print $1}')
  log "✓ Build successful: $OUT ($SIZE)"
  log "Install on a connected device: adb install -r \"$OUT\""
else
  err "Build finished but APK not found at expected path."
  exit 1
fi
